name: Linux x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_ACTIVE: "FALSE"   # prevent renv from hijacking the session

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4"
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y python3-venv python3-dev python3-pip cmake ninja-build g++

      - name: Install R packages
        run: |
          Rscript -e "
            install.packages('remotes')
            remotes::install_github('keneo/play-zvec/rzvec')
            remotes::install_github('keneo/play-zvec/rszvec')
          "

      - name: Run end-to-end test
        run: Rscript docker/ci-test.R

  test-bb:
    runs-on: self-hosted

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_ACTIVE: "FALSE"

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4"
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y python3-venv python3-dev python3-pip cmake ninja-build g++

      - name: Install R packages
        run: |
          Rscript -e "
            install.packages('remotes')
            remotes::install_github('keneo/play-zvec/rzvec')
            remotes::install_github('keneo/play-zvec/rszvec')
          "

      - name: Run end-to-end test
        run: Rscript docker/ci-test.R
